# Generated by Django 4.2.7 on 2025-11-24 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('integrity_status', models.CharField(choices=[('OK', 'OK'), ('ANOMALY', 'Anomaly Detected'), ('OUT_OF_RANGE', 'Out of Range'), ('LOW_CONFIDENCE', 'Low Confidence'), ('TAMPERED', 'Tampered')], default='OK', max_length=20)),
                ('details', models.TextField(help_text='Detailed description of the security event')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cyber_logs', to='soil.soilinput')),
            ],
            options={
                'verbose_name': 'Cyber Log',
                'verbose_name_plural': 'Cyber Logs',
                'db_table': 'cyber_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(help_text='Description of admin action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Logs',
                'db_table': 'admin_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
